apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pro.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: k8stest-pymom-register-dev
  name: k8stest-pymom-register-dev
  namespace: k8stest-pymom-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: k8stest-pymom-register-dev
    spec:
      containers:
      - command:
        - java
        - -jar
        - -Xms128m
        - -Xmx256m
        - /java8/app.jar
        - --spring.profiles.active=pro
        - --server.port=5000
        - --eureka.client.register-with-eureka=false
        - --eureka.client.fetch-registry=false
        - --eureka.instance.prefer-ip-address=true
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        image: harbor.pycf.com/k8stest-pymom/register:latest
        imagePullPolicy: Always
        name: k8stest-pymom-register-dev
        ports:
        - containerPort: 5000
        resources: {}
      imagePullSecrets:
      - name: harborkey1
      restartPolicy: Always

status: {}