apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pro.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: k8stest-pymom-manager-pro
  name: k8stest-pymom-manager-pro
  namespace: k8stest-pymom-pro
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: k8stest-pymom-manager-pro
    spec:
      containers:
      - command:
        - java
        - -jar
        - -Xms128m
        - -Xmx256m
        - /java8/app.jar
        - --spring.profiles.active=pro
        - --server.port=5000
        - --eureka.instance.prefer-ip-address=true
        - --eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}
        - --eureka.client.service-url.defaultZone=http://register:6553/eureka/
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        image: harbor.pycf.com/k8stest-pymom/manager:latest
        name: k8stest-pymom-manager-pro
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: harborkey1
      restartPolicy: Always

status: {}